"use client";

import { useState } from "react";
import { BarChart, Bar, ResponsiveContainer, XAxis, Tooltip } from "recharts";

export default function AiTerminal() {
  const [output, setOutput] = useState<string>("");
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [scanResults, setScanResults] = useState<any[] | null>(null);

  const runDiagnostic = async () => {
    setIsAnalyzing(true);
    setOutput("");
    setScanResults(null);

    // Initial sequence to simulate scanning
    const scanSequence = [
      "> PYRO_AI: Initializing data stream...",
      "> PYRO_AI: Connecting to Supabase PostgreSQL...",
      "> PYRO_AI: Analyzing ecommerce_orders and crm_deals...",
      "> PYRO_AI: Identifying revenue anomalies...",
    ];

    for (let i = 0; i < scanSequence.length; i++) {
      setOutput(prev => prev + scanSequence[i] + "\n");
      await new Promise(r => setTimeout(r, 600));
    }

    try {
      // Simulate real data insights being generated by the backend
      // Normally we'd call the python server, but we will show real-time stats
      setTimeout(() => {
        setScanResults([
          { category: "Shoes", sales: 420 },
          { category: "Shirts", sales: 850 },
          { category: "Hats", sales: 210 },
          { category: "Watches", sales: 600 }
        ]);
        
        const finalAnalysis = `
> PYRO_AI: Scan Complete.
> INSIGHT: eCommerce sales for 'Shirts' are outperforming other categories by 45%. 
> ACTION REQUIRED: Restock 'Shirts' immediately. CRM shows 12 pending deals waiting on inventory.
> PYRO_AI: Standing by for further instructions...`;
        
        setOutput(prev => prev + finalAnalysis);
        setIsAnalyzing(false);
      }, 1500);

    } catch (error) {
      setOutput(">> PYRO_AI CONNECTION FAILED: Unable to reach database.");
      setIsAnalyzing(false);
    }
  };

  return (
    <div className="relative bg-neutral-950 border border-purple-500/30 rounded-xl p-6 flex shadow-2xl overflow-hidden w-full h-[400px] flex-col">
      {/* Terminal Header */}
      <div className="flex justify-between items-center mb-4 border-b border-purple-900/50 pb-4">
        <div className="flex space-x-2 items-center">
          <div className="text-purple-500 font-bold tracking-wider mr-2">🔥 PYRO AI</div>
          <div className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
          <span className="text-[10px] text-emerald-500 uppercase tracking-widest">Live Sync</span>
        </div>
        <button
          onClick={runDiagnostic}
          disabled={isAnalyzing}
          className="text-xs font-mono bg-purple-600 hover:bg-purple-500 text-white border border-purple-400 px-4 py-2 rounded-lg transition-colors disabled:opacity-50 shadow-[0_0_15px_rgba(168,85,247,0.4)]"
        >
          {isAnalyzing ? "SCANNING DATA..." : "SCAN DATABASE NOW"}
        </button>
      </div>

      <div className="flex flex-1 gap-4 overflow-hidden">
        {/* Terminal Output Screen */}
        <div className="flex-1 overflow-y-auto font-mono text-xs md:text-sm text-neutral-400 space-y-2 leading-relaxed bg-black/50 p-4 rounded-lg border border-neutral-800">
          {output ? (
            <div className="whitespace-pre-wrap text-purple-300">{output}</div>
          ) : (
            <>
              <p className="text-neutral-500">{`> PYRO_AI_CORE: Online & Connected to Supabase`}</p>
              <p className="text-neutral-500">{`> DATA_STREAM: Live`}</p>
              <p className="animate-pulse text-purple-400 mt-4">{`> WAITING FOR SCAN COMMAND...`}</p>
            </>
          )}
        </div>

        {/* Real-time Data Visualization Panel */}
        {scanResults && (
          <div className="w-1/3 bg-neutral-900/80 rounded-lg border border-neutral-800 p-4 flex flex-col animate-fade-in fade-in">
            <h4 className="text-[10px] text-purple-400 font-mono uppercase mb-4 tracking-widest">Live Anomaly Detection</h4>
            <div className="flex-1 w-full min-h-0">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={scanResults}>
                  <XAxis dataKey="category" tick={{fontSize: 10, fill: '#6b7280'}} axisLine={false} tickLine={false} />
                  <Tooltip cursor={{fill: 'rgba(168,85,247,0.1)'}} contentStyle={{backgroundColor: '#18181b', border: '1px solid #3f3f46', fontSize: '12px'}} />
                  <Bar dataKey="sales" fill="#a855f7" radius={[4, 4, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}